kramdown:
  input: GFM

exclude: ["node_modules", "gulpfile.js", "package.json", "Gemfile", "Gemfile.lock"]
include: ["_redirects"]

social-links:
  twitter: 'https://twitter.com/netlify'
  facebook: 'https://www.facebook.com/netlify'
  github: 'https://github.com/netlify'
  linkedin: 'https://www.linkedin.com/company/netlify'
  googleplus: 'https://plus.google.com/+NetlifyApp'

excerpt_separator: <!-- excerpt -->

cms: local

collections:
  docs:
    output: true

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      permalink: /blog/:year/:month/:day/:title.html
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "docs"

# RSS
rss:
  name: The netlify blog. All about static web-tech and netlify
  url: https://www.netlify.com
  path: /blog
