url: https://www.netlify.com
name: The netlify blog. All about static web-tech and netlify
author: Netlify

future: false

kramdown:
  input: GFM

exclude: ["node_modules", "gulpfile.js", "package.json", "Gemfile", "Gemfile.lock", "status.html", "status-cms", "admin-status"]
include: ["_redirects"]

social-links:
  twitter: 'https://twitter.com/netlify'
  facebook: 'https://www.facebook.com/netlify'
  github: 'https://github.com/netlify'
  linkedin: 'https://www.linkedin.com/company/netlify'
  gitter: 'https://gitter.im/netlify/community'

excerpt_separator: <!-- excerpt -->

collections:
  docs:
    output: true
  reseller_docs:
    output: true
    permalink: /reseller/docs/:title.html
  incidents:
    output: false


defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      permalink: /blog/:year/:month/:day/:title.html
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "docs"
  - scope:
      path: ""
      type: "reseller_docs"
    values:
      layout: "reseller_docs"

# RSS
rss_path: /blog
gems:
  - jekyll-srcset
  - octopress-minify-html
  - jekyll-feed
minify_html: false

srcset:
  cache: /tmp/nf-home-cache
