backend:
  name: github-api
  repo: netlify/netlify-home
  branch: master

media_folder: uploads

collections:
  - name: "post"
    label: "Blog Post"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1", class: "post-title"}
      - {label: "Author", name: "author", widget: "string", preview: "author", tagname: "p", class: "post-meta"}
      - {label: "Cover Image", name: "image", widget: "image", tagname: "div", class: "post-img", folder: "img/posts", optional: true}
      - {label: "Post Body", name: "body", widget: "markdown", tagname: "div", class: "post-bd"}
      - {label: "Short Title", name: "short_title", widget: "string", tagname: "h1", class: "blurb-title"}
      - {label: "Description", name: "description", widget: "string", tagname: "p", class: "small muted"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", tagname: "div", class: "media-img optional cms-thumbnail", folder: "img/posts/thumbnails"}
    meta:
      - {label: "Tags (seperated by comma)", name: "tags", widget: "tags"}


  - name: "docs"
    label: "Doc Pages"
    folder: "_docs"
    create: true
    fields:
      - {label: "Post Body", name: "body", widget: "markdown", tagname: "div", class: "post-bd"}
    meta:
      - {label: "Menu Title", name: "title", widget: "string", optional: false}
      - {label: "Position", name: "position", widget: "number", optional: false}
