backend:
  name: netlify-api
  url: http://localhost:8080

staging:
  backend:
    name: github-api
    repo: netlify/netlify-home
    branch: staging

production:
  backend:
    name: github-api
    repo: netlify/netlify-home
    branch: master
  
media_folder: uploads

collections:
  - name: "post"
    label: "Blog Post"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    sort: "date:desc"
    fields:
      - {label: "Title", name: "title", widget: "string", tagname: "h1", class: "post-title"}
      - {label: "Author", name: "author", widget: "string", preview: "author", tagname: "p", class: "post-meta"}
      - {label: "Cover Image", name: "image", widget: "image", tagname: "div", class: "post-img", folder: "img/posts", optional: true}
      - {label: "Post Body", name: "body", widget: "markdown", tagname: "div", class: "post-bd text"}
      - {label: "Short Title", name: "short_title", widget: "string", tagname: "h1", class: "blurb-title"}
      - {label: "Description", name: "description", widget: "string", tagname: "p", class: "small muted"}
      - {label: "Thumbnail", name: "thumbnail", widget: "image", tagname: "div", class: "media-img optional cms-thumbnail", folder: "img/posts/thumbnails"}
    meta:
      - {label: "Tags (seperated by comma)", name: "tags", widget: "tags"}

  - name: "docs"
    label: "Docs"
    folder: "_docs"
    create: true
    sort: "position:asc"
    fields:
      - {label: "Body", name: "body", widget: "markdown", tagname: "div", class: "docs-main text"}
    meta:
      - {label: "Menu Title", name: "title", widget: "string", optional: false}
      - {label: "Position", name: "position", widget: "number", optional: false}

  - name: "data"
    label: "Misc"
    files:
      - name: testimonials
        label: Testimonials
        file: _data/testimonials.yml
        fields:
          - name: quotes
            label: Testimonials
            description: "Quotes, Titles, Photos and Links for the testimonials"
            widget: list
            fields:
              - {label: "Quote", name: "quote", widget: "markdown"}
              - {label: "Name and title", name: "cite", widget: "string"}
              - {label: "Link URL", name: "link", widget: "string"}
              - {label: "Photo", name: "photo", widget: "image", media_folder: "img/testimonials"}
